version: "3.7"
services:
  api:
    container_name: api
    build: ./api/
    links:
      - db
    environment:
      - DATABASE_URL=postgres://api:123@db:5432/postgres
    command: npm start
    ports:
      - "80:80"
    volumes:
      - ./api:/web
  db:
    image: postgres
    container_name: db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=123

    